export const lessonOne = {
  lessonNumber: "1",
  titleChinese: "你叫什么名字？",
  titleEnglish: " What is your name?",
  convoLineOne: "你好。",
  convoLineTwo: "您好。",
  convoLineThree: "你叫什么名字？",
  convoLineFour: "我叫朱虹。你叫什么名字？",
  convoLineFive: "我叫刘明。",
  translationChinWordOne: "你",
  translationPinWordOne: "nǐ",
  translationEngWordOne: "you",
  translationChinWordTwo: "好",
  translationPinWordTwo: "hǎo",
  translationEngWordTwo: "good",
  translationChinWordThree: "你好",
  translationPinWordThree: "nǐ hǎo",
  translationEngWordThree: "hello",
  translationChinWordFour: "您",
  translationPinWordFour: "nín",
  translationEngWordFour: "you (polite)",
  translationChinWordFive: "您好",
  translationPinWordFive: "nínhǎo",
  translationEngWordFive: "hello (polite)",
  translationChinWordSix: "叫",
  translationPinWordSix: "jiào",
  translationEngWordSix: "called, named",
  translationChinWordSeven: "什么",
  translationPinWordSeven: "shénme",
  translationEngWordSeven: "what",
  translationChinWordEight: "名字",
  translationPinWordEight: "míngzi",
  translationEngWordEight: "name",
  translationChinWordNine: "我",
  translationPinWordNine: "wǒ",
  translationEngWordNine: "I",
  translationChinWordTen: "朱虹",
  translationPinWordTen: "zhū hóng",
  translationEngWordTen: "a female name",
  translationChinWordEleven: "刘明",
  translationPinWordEleven: "líu míng",
  translationEngWordEleven: "a male name",
  sentanceTranslationPinOne: "Nǐ hǎo.",
  sentanceTranslationEngOne: "Hello.",
  sentanceTranslationPinTwo: "Nínhǎo.",
  sentanceTranslationEngTwo: "Hello.",
  sentanceTranslationPinThree: "Nǐ jìao shénme míngzi?",
  sentanceTranslationEngThree: "What is your name?",
  sentanceTranslationPinFour: "Wǒ jìao Zhū Hóng. Nǐ jìao shénme míngzi?",
  sentanceTranslationEngFour: "I’m called Zhu Hong. What is your name?",
  sentanceTranslationPinFive: "Wǒ jìao Líu Míng.",
  sentanceTranslationEngFive: "I’m called Liu Ming.",
  keyPhraseChinOne: "你好。",
  keyPhrasePinOne: "Nǐ hǎo.",
  keyPhraseEngOne: "Hello.",
  keyPhraseChinTwo: "您好。",
  keyPhrasePinTwo: "Nínhǎo.",
  keyPhraseEngTwo: "Hello (polite).",
  keyPhraseChinThree: "你叫什么名字？",
  keyPhrasePinThree: "Nǐ jìao shénme míngzi?",
  keyPhraseEngThree: "What is your name?",
  keyPhraseChinFour: "我叫......",
  keyPhrasePinFour: "Wǒ jìao...",
  keyPhraseEngFour: "I’m called...",
  firstSpeakerMale: true,
};

export const lessonTwo = {
  lessonNumber: "2",
  titleChinese: "你是中国人吗？",
  titleEnglish: "Are you Chinese?",
  convoLineOne: "您贵姓？",
  convoLineTwo: "我姓朱。",
  convoLineThree: "你是中国人吗?",
  convoLineFour: "是的，我是中国人。你是美国人吗？",
  convoLineFive: "是的，我是美国人。",
  translationChinWordOne: "贵",
  translationPinWordOne: "guì",
  translationEngWordOne: "expensive, honorable",
  translationChinWordTwo: "姓",
  translationPinWordTwo: "xìng",
  translationEngWordTwo: "surname",
  translationChinWordThree: "贵姓",
  translationPinWordThree: "guìxìng",
  translationEngWordThree: "surname (polite)",
  translationChinWordFour: "是",
  translationPinWordFour: "shì",
  translationEngWordFour: "is, be, am",
  translationChinWordFive: "国",
  translationPinWordFive: "guó",
  translationEngWordFive: "country, nation",
  translationChinWordSix: "中国",
  translationPinWordSix: "zhōngguó",
  translationEngWordSix: "China",
  translationChinWordSeven: "人",
  translationPinWordSeven: "rén",
  translationEngWordSeven: "person",
  translationChinWordEight: "中国人",
  translationPinWordEight: "zhōngguórén",
  translationEngWordEight: "Chinese",
  translationChinWordNine: "吗",
  translationPinWordNine: "ma",
  translationEngWordNine: "(used at the end of a question)",
  translationChinWordTen: "是的",
  translationPinWordTen: "shìde",
  translationEngWordTen: "yes",
  translationChinWordEleven: "美",
  translationPinWordEleven: "měi",
  translationEngWordEleven: "beautiful",
  translationChinWordTwelve: "美国",
  translationPinWordTwelve: "měiguó",
  translationEngWordTwelve: "USA",
  sentanceTranslationPinOne: "Nín guìxìng?",
  sentanceTranslationEngOne: "What is your surname?",
  sentanceTranslationPinTwo: "Wǒ xìng zhū.",
  sentanceTranslationEngTwo: "My surname is Zhu.",
  sentanceTranslationPinThree: "Nǐ shì zhōngguórén ma?",
  sentanceTranslationEngThree: "Are you Chinese?",
  sentanceTranslationPinFour: "Shìde. Wǒ shì zhōngguórén. Nǐ shì měiguórén ma?",
  sentanceTranslationEngFour: "Yes. I am Chinese. Are you American?",
  sentanceTranslationPinFive: "Shìde. Wǒ shì měiguórén.",
  sentanceTranslationEngFive: "Yes. I am American",
  keyPhraseChinOne: "您贵姓？",
  keyPhrasePinOne: "Nín guìxìng?",
  keyPhraseEngOne: "What is your surname?",
  keyPhraseChinTwo: "我姓......",
  keyPhrasePinTwo: "Wǒ xìng…",
  keyPhraseEngTwo: "My surname is…",
  keyPhraseChinThree: "你是中国人吗？",
  keyPhrasePinThree: "Nǐ shì zhōngguórén ma?",
  keyPhraseEngThree: "Are you Chinese?",
  keyPhraseChinFour: "是的。",
  keyPhrasePinFour: "Shìde.",
  keyPhraseEngFour: "Yes.",
  keyPhraseChinFive: "我是中国人。",
  keyPhrasePinFive: "Wǒ shì zhōngguórén.",
  keyPhraseEngFive: "I am Chinese.",
  firstSpeakerMale: true,
};

export const lessonThree = {
  lessonNumber: "3",
  titleChinese: "她是谁？",
  titleEnglish: "Who is she?",
  convoLineOne: "她是谁？",
  convoLineTwo: "她是明美。",
  convoLineThree: "她是韩国人吗？",
  convoLineFour: "不是。她是日本人。",
  convoLineFive: "哦，她是老师吗？",
  convoLineSix: "不是，她不是老师。她是学生。",
  convoLineSeven: "谁是老师？",
  convoLineEight: "他是老师。",
  translationChinWordOne: "她",
  translationPinWordOne: "tā",
  translationEngWordOne: "she",
  translationChinWordTwo: "谁",
  translationPinWordTwo: "shéi",
  translationEngWordTwo: "who",
  translationChinWordThree: "明美",
  translationPinWordThree: "míngměi",
  translationEngWordThree: "a female name",
  translationChinWordFour: "韩国",
  translationPinWordFour: "hánguó",
  translationEngWordFour: "Korea",
  translationChinWordFive: "日本",
  translationPinWordFive: "rìběn",
  translationEngWordFive: "Japan",
  translationChinWordSix: "哦",
  translationPinWordSix: "ò",
  translationEngWordSix: "oh (use to express understanding)",
  translationChinWordSeven: "老师",
  translationPinWordSeven: "lǎoshī",
  translationEngWordSeven: "teacher",
  translationChinWordEight: "不",
  translationPinWordEight: "bù",
  translationEngWordEight: "not, no",
  translationChinWordNine: "不是",
  translationPinWordNine: "búshì",
  translationEngWordNine: "is not, to not be",
  translationChinWordTen: "学生",
  translationPinWordTen: "xuésheng",
  translationEngWordTen: "student",
  translationChinWordEleven: "他",
  translationPinWordEleven: "tā",
  translationEngWordEleven: "he",
  sentanceTranslationPinOne: "Tā shì shéi?",
  sentanceTranslationEngOne: "Who is she?",
  sentanceTranslationPinTwo: "Tā shì míngměi.",
  sentanceTranslationEngTwo: "She is Ming Mei.",
  sentanceTranslationPinThree: "Tā shì hánguórén ma?.",
  sentanceTranslationEngThree: "Is she Korean?",
  sentanceTranslationPinFour: "Búshì. Tā shì rìběnrén.",
  sentanceTranslationEngFour: "No. She is Japanese.",
  sentanceTranslationPinFive: "Ò, tā shì lǎoshī ma?",
  sentanceTranslationEngFive: " Oh. Is she a teacher?",
  sentanceTranslationPinSix: "Búshì, tā búshì lǎoshī. Tā shì xuésheng.",
  sentanceTranslationEngSix: "No. She is not a teacher. She is a student",
  sentanceTranslationPinSeven: "Shéi shì lǎoshī?",
  sentanceTranslationEngSeven: "Who is the teacher?",
  sentanceTranslationPinEight: "Tā shì lǎoshī.",
  sentanceTranslationEngEight: " He is the teacher",
  keyPhraseChinOne: "她/他是谁？",
  keyPhrasePinOne: "Tā/tā shì sheí?",
  keyPhraseEngOne: "Who is she/he?",
  keyPhraseChinTwo: "她/他是......",
  keyPhrasePinTwo: "Tā/tā shì...",
  keyPhraseEngTwo: "She/he is…",
  keyPhraseChinThree: "她/他是老师吗？",
  keyPhrasePinThree: "Tā/tā shì lǎoshī ma?",
  keyPhraseEngThree: "Is she/he a teacher?",
  keyPhraseChinFour: "不是。",
  keyPhrasePinFour: "Búshì.",
  keyPhraseEngFour: "No.",
  keyPhraseChinFive: "她/他不是老师。",
  keyPhrasePinFive: "Tā/tā búshì lǎoshī.",
  keyPhraseEngFive: "She/he is not a teacher",
  firstSpeakerMale: true,
};

export const lessonFour = {
  lessonNumber: "4",
  titleChinese: "认识你很高兴",
  titleEnglish: "Nice to meet you",
  convoLineOne: "李先生，认识你很高兴。",
  convoLineTwo: "我也很高兴。",
  convoLineThree: "你是学生还是老师？",
  convoLineFour: "我是留学生。",
  convoLineFive: "你是中国人还是韩国人？",
  convoLineSix: "我是英国人。",
  convoLineSeven: "哦。",
  translationChinWordOne: "李",
  translationPinWordOne: "Lǐ",
  translationEngWordOne: "a surname",
  translationChinWordTwo: "先生",
  translationPinWordTwo: "xiānsheng",
  translationEngWordTwo: "Mr.",
  translationChinWordThree: "认识",
  translationPinWordThree: "rènshi",
  translationEngWordThree: "recognize",
  translationChinWordFour: "很",
  translationPinWordFour: "hěn",
  translationEngWordFour: "very",
  translationChinWordFive: "高兴",
  translationPinWordFive: "gāoxìng",
  translationEngWordFive: "happy",
  translationChinWordSix: "认识你很高兴",
  translationPinWordSix: "rènshi nǐ hěn gāoxìng",
  translationEngWordSix: "nice to meet you",
  translationChinWordSeven: "也",
  translationPinWordSeven: "yě",
  translationEngWordSeven: "also",
  translationChinWordEight: "还是",
  translationPinWordEight: "háishì",
  translationEngWordEight: "or",
  translationChinWordNine: "留学生",
  translationPinWordNine: "liúxuéshēng",
  translationEngWordNine: "foreign student",
  translationChinWordTen: "英国",
  translationPinWordTen: "yīngguó",
  translationEngWordTen: "Britain",
  sentanceTranslationPinOne: "Lǐ xiānsheng, rènshi nǐ hěn gāoxìng.",
  sentanceTranslationEngOne: "Mr. Li, nice to meet you.",
  sentanceTranslationPinTwo: "wǒ yě hěn gāoxìng.",
  sentanceTranslationEngTwo: "I am also happy.",
  sentanceTranslationPinThree: "nǐ shì xuéshēng háishì lǎoshī?",
  sentanceTranslationEngThree: "Are you a student or a teacher?",
  sentanceTranslationPinFour: "wǒ shì liúxuéshēng.",
  sentanceTranslationEngFour: "I am a foreign student.",
  sentanceTranslationPinFive: "nǐ shì zhōngguórén háishì hánguórén?.",
  sentanceTranslationEngFive: "Are you Chinese or Korean?",
  sentanceTranslationPinSix: "wǒ shì yīngguórén.",
  sentanceTranslationEngSix: "I am British.",
  sentanceTranslationPinSeven: "Ò.",
  sentanceTranslationEngSeven: "oh.",
  keyPhraseChinOne: "认识你很高兴。",
  keyPhrasePinOne: "Rènshi nǐ hěn gāoxìng.",
  keyPhraseEngOne: "Nice to meet you.",
  keyPhraseChinTwo: "我也很高兴。",
  keyPhrasePinTwo: "Wǒ yě hěn gāoxìng.",
  keyPhraseEngTwo: "I am also happy.",
  keyPhraseChinThree: "你是学生还是老师？",
  keyPhrasePinThree: "Nǐ shì xuésheng háishì lǎoshī?",
  keyPhraseEngThree: "Are you a student or a teacher?",
  firstSpeakerMale: false,
};

export const lessonFive = {
  lessonNumber: "5",
  titleChinese: "请进",
  titleEnglish: "Come in",
  convoLineOne: "张女士, 请进。",
  convoLineTwo: "您好。",
  convoLineThree: "请坐。",
  convoLineFour: "谢谢。",
  convoLineFive: "不客气。",
  translationChinWordOne: "张",
  translationPinWordOne: "zhāng",
  translationEngWordOne: "a surname",
  translationChinWordTwo: "女士",
  translationPinWordTwo: "nǚshì",
  translationEngWordTwo: "Mrs.",
  translationChinWordThree: "请",
  translationPinWordThree: "qǐng",
  translationEngWordThree: "please",
  translationChinWordFour: "进",
  translationPinWordFour: "jìn",
  translationEngWordFour: "enter",
  translationChinWordFive: "请进",
  translationPinWordFive: "qǐng jìn",
  translationEngWordFive: "please come in",
  translationChinWordSix: "坐",
  translationPinWordSix: "zuò",
  translationEngWordSix: "sit",
  translationChinWordSeven: "请坐",
  translationPinWordSeven: "qǐng zuò",
  translationEngWordSeven: "please sit down",
  translationChinWordEight: "谢谢",
  translationPinWordEight: "xièxiè",
  translationEngWordEight: "thank you",
  translationChinWordNine: "客气",
  translationPinWordNine: "kèqi",
  translationEngWordNine: "polite",
  translationChinWordTen: "不客气",
  translationPinWordTen: "búkèqi",
  translationEngWordTen: "it’s OK, you are welcome",
  sentanceTranslationPinOne: "Zhāng nǚshì qǐng jìn.",
  sentanceTranslationEngOne: "Mrs. Zhang, please come in.",
  sentanceTranslationPinTwo: "Nínhǎo.",
  sentanceTranslationEngTwo: "Hello.",
  sentanceTranslationPinThree: "Qǐng zuò.",
  sentanceTranslationEngThree: "Please sit.",
  sentanceTranslationPinFour: "Xièxiè.",
  sentanceTranslationEngFour: "Thank you.",
  sentanceTranslationPinFive: "Búkèqi.",
  sentanceTranslationEngFive: "It’s OK.",
  keyPhraseChinOne: "请进 。",
  keyPhrasePinOne: "Qǐng jìn.",
  keyPhraseEngOne: "Please come in.",
  keyPhraseChinTwo: "请坐 。",
  keyPhrasePinTwo: "Qǐng zuò.",
  keyPhraseEngTwo: "Please sit.",
  keyPhraseChinThree: "谢谢 。",
  keyPhrasePinThree: "Xièxiè.",
  keyPhraseEngThree: "Thank you.",
  keyPhraseChinFour: "不客气 。",
  keyPhrasePinFour: "Búkèqi.",
  keyPhraseEngFour: "It’s OK",
  firstSpeakerMale: true,
};

// array of objects

export const arrayOfLessons = [
  {
    lessonNumber: "1",
    titleChinese: "你叫什么名字？",
    titleEnglish: "What is your name?",
    convoLineOne: "你好。",
    convoLineTwo: "您好。",
    convoLineThree: "你叫什么名字？",
    convoLineFour: "我叫朱虹。你叫什么名字？",
    convoLineFive: "我叫刘明。",
    translationChinWordOne: "你",
    translationPinWordOne: "nǐ",
    translationEngWordOne: "you",
    translationChinWordTwo: "好",
    translationPinWordTwo: "hǎo",
    translationEngWordTwo: "good",
    translationChinWordThree: "你好",
    translationPinWordThree: "nǐ hǎo",
    translationEngWordThree: "hello",
    translationChinWordFour: "您",
    translationPinWordFour: "nín",
    translationEngWordFour: "you (polite)",
    translationChinWordFive: "您好",
    translationPinWordFive: "nínhǎo",
    translationEngWordFive: "hello (polite)",
    translationChinWordSix: "叫",
    translationPinWordSix: "jiào",
    translationEngWordSix: "called, named",
    translationChinWordSeven: "什么",
    translationPinWordSeven: "shénme",
    translationEngWordSeven: "what",
    translationChinWordEight: "名字",
    translationPinWordEight: "míngzi",
    translationEngWordEight: "name",
    translationChinWordNine: "我",
    translationPinWordNine: "wǒ",
    translationEngWordNine: "I",
    translationChinWordTen: "朱虹",
    translationPinWordTen: "zhū hóng",
    translationEngWordTen: "a female name",
    translationChinWordEleven: "刘明",
    translationPinWordEleven: "líu míng",
    translationEngWordEleven: "a male name",
    sentanceTranslationPinOne: "Nǐ hǎo.",
    sentanceTranslationEngOne: "Hello.",
    sentanceTranslationPinTwo: "Nínhǎo.",
    sentanceTranslationEngTwo: "Hello.",
    sentanceTranslationPinThree: "Nǐ jìao shénme míngzi?",
    sentanceTranslationEngThree: "What is your name?",
    sentanceTranslationPinFour: "Wǒ jìao Zhū Hóng. Nǐ jìao shénme míngzi?",
    sentanceTranslationEngFour: "I’m called Zhu Hong. What is your name?",
    sentanceTranslationPinFive: "Wǒ jìao Líu Míng.",
    sentanceTranslationEngFive: "I’m called Liu Ming.",
    keyPhraseChinOne: "你好。",
    keyPhrasePinOne: "Nǐ hǎo.",
    keyPhraseEngOne: "Hello.",
    keyPhraseChinTwo: "您好。",
    keyPhrasePinTwo: "Nínhǎo.",
    keyPhraseEngTwo: "Hello (polite).",
    keyPhraseChinThree: "你叫什么名字？",
    keyPhrasePinThree: "Nǐ jìao shénme míngzi?",
    keyPhraseEngThree: "What is your name?",
    keyPhraseChinFour: "我叫......",
    keyPhrasePinFour: "Wǒ jìao...",
    keyPhraseEngFour: "I’m called...",
    firstSpeakerMale: true,
  },
  {
    lessonNumber: "2",
    titleChinese: "你是中国人吗？",
    titleEnglish: "Are you Chinese?",
    convoLineOne: "您贵姓？",
    convoLineTwo: "我姓朱。",
    convoLineThree: "你是中国人吗?",
    convoLineFour: "是的，我是中国人。你是美国人吗？",
    convoLineFive: "是的，我是美国人。",
    translationChinWordOne: "贵",
    translationPinWordOne: "guì",
    translationEngWordOne: "expensive, honorable",
    translationChinWordTwo: "姓",
    translationPinWordTwo: "xìng",
    translationEngWordTwo: "surname",
    translationChinWordThree: "贵姓",
    translationPinWordThree: "guìxìng",
    translationEngWordThree: "surname (polite)",
    translationChinWordFour: "是",
    translationPinWordFour: "shì",
    translationEngWordFour: "is, be, am",
    translationChinWordFive: "国",
    translationPinWordFive: "guó",
    translationEngWordFive: "country, nation",
    translationChinWordSix: "中国",
    translationPinWordSix: "zhōngguó",
    translationEngWordSix: "China",
    translationChinWordSeven: "人",
    translationPinWordSeven: "rén",
    translationEngWordSeven: "person",
    translationChinWordEight: "中国人",
    translationPinWordEight: "zhōngguórén",
    translationEngWordEight: "Chinese",
    translationChinWordNine: "吗",
    translationPinWordNine: "ma",
    translationEngWordNine: "(used at the end of a question)",
    translationChinWordTen: "是的",
    translationPinWordTen: "shìde",
    translationEngWordTen: "yes",
    translationChinWordEleven: "美",
    translationPinWordEleven: "měi",
    translationEngWordEleven: "beautiful",
    translationChinWordTwelve: "美国",
    translationPinWordTwelve: "měiguó",
    translationEngWordTwelve: "USA",
    sentanceTranslationPinOne: "Nín guìxìng?",
    sentanceTranslationEngOne: "What is your surname?",
    sentanceTranslationPinTwo: "Wǒ xìng zhū.",
    sentanceTranslationEngTwo: "My surname is Zhu.",
    sentanceTranslationPinThree: "Nǐ shì zhōngguórén ma?",
    sentanceTranslationEngThree: "Are you Chinese?",
    sentanceTranslationPinFour:
      "Shìde. Wǒ shì zhōngguórén. Nǐ shì měiguórén ma?",
    sentanceTranslationEngFour: "Yes. I am Chinese. Are you American?",
    sentanceTranslationPinFive: "Shìde. Wǒ shì měiguórén.",
    sentanceTranslationEngFive: "Yes. I am American",
    keyPhraseChinOne: "您贵姓？",
    keyPhrasePinOne: "Nín guìxìng?",
    keyPhraseEngOne: "What is your surname?",
    keyPhraseChinTwo: "我姓......",
    keyPhrasePinTwo: "Wǒ xìng…",
    keyPhraseEngTwo: "My surname is…",
    keyPhraseChinThree: "你是中国人吗？",
    keyPhrasePinThree: "Nǐ shì zhōngguórén ma?",
    keyPhraseEngThree: "Are you Chinese?",
    keyPhraseChinFour: "是的。",
    keyPhrasePinFour: "Shìde.",
    keyPhraseEngFour: "Yes.",
    keyPhraseChinFive: "我是中国人。",
    keyPhrasePinFive: "Wǒ shì zhōngguórén.",
    keyPhraseEngFive: "I am Chinese.",
    firstSpeakerMale: true,
  },
  {
    lessonNumber: "3",
    titleChinese: "她是谁？",
    titleEnglish: "Who is she?",
    convoLineOne: "她是谁？",
    convoLineTwo: "她是明美。",
    convoLineThree: "她是韩国人吗？",
    convoLineFour: "不是。她是日本人。",
    convoLineFive: "哦，她是老师吗？",
    convoLineSix: "不是，她不是老师。她是学生。",
    convoLineSeven: "谁是老师？",
    convoLineEight: "他是老师。",
    translationChinWordOne: "她",
    translationPinWordOne: "tā",
    translationEngWordOne: "she",
    translationChinWordTwo: "谁",
    translationPinWordTwo: "shéi",
    translationEngWordTwo: "who",
    translationChinWordThree: "明美",
    translationPinWordThree: "míngměi",
    translationEngWordThree: "a female name",
    translationChinWordFour: "韩国",
    translationPinWordFour: "hánguó",
    translationEngWordFour: "Korea",
    translationChinWordFive: "日本",
    translationPinWordFive: "rìběn",
    translationEngWordFive: "Japan",
    translationChinWordSix: "哦",
    translationPinWordSix: "ò",
    translationEngWordSix: "oh (use to express understanding)",
    translationChinWordSeven: "老师",
    translationPinWordSeven: "lǎoshī",
    translationEngWordSeven: "teacher",
    translationChinWordEight: "不",
    translationPinWordEight: "bù",
    translationEngWordEight: "not, no",
    translationChinWordNine: "不是",
    translationPinWordNine: "búshì",
    translationEngWordNine: "is not, to not be",
    translationChinWordTen: "学生",
    translationPinWordTen: "xuésheng",
    translationEngWordTen: "student",
    translationChinWordEleven: "他",
    translationPinWordEleven: "tā",
    translationEngWordEleven: "he",
    sentanceTranslationPinOne: "Tā shì shéi?",
    sentanceTranslationEngOne: "Who is she?",
    sentanceTranslationPinTwo: "Tā shì míngměi.",
    sentanceTranslationEngTwo: "She is Ming Mei.",
    sentanceTranslationPinThree: "Tā shì hánguórén ma?.",
    sentanceTranslationEngThree: "Is she Korean?",
    sentanceTranslationPinFour: "Búshì. Tā shì rìběnrén.",
    sentanceTranslationEngFour: "No. She is Japanese.",
    sentanceTranslationPinFive: "Ò, tā shì lǎoshī ma?",
    sentanceTranslationEngFive: " Oh. Is she a teacher?",
    sentanceTranslationPinSix: "Búshì, tā búshì lǎoshī. Tā shì xuésheng.",
    sentanceTranslationEngSix: "No. She is not a teacher. She is a student",
    sentanceTranslationPinSeven: "Shéi shì lǎoshī?",
    sentanceTranslationEngSeven: "Who is the teacher?",
    sentanceTranslationPinEight: "Tā shì lǎoshī.",
    sentanceTranslationEngEight: " He is the teacher",
    keyPhraseChinOne: "她/他是谁？",
    keyPhrasePinOne: "Tā/tā shì sheí?",
    keyPhraseEngOne: "Who is she/he?",
    keyPhraseChinTwo: "她/他是......",
    keyPhrasePinTwo: "Tā/tā shì...",
    keyPhraseEngTwo: "She/he is…",
    keyPhraseChinThree: "她/他是老师吗？",
    keyPhrasePinThree: "Tā/tā shì lǎoshī ma?",
    keyPhraseEngThree: "Is she/he a teacher?",
    keyPhraseChinFour: "不是。",
    keyPhrasePinFour: "Búshì.",
    keyPhraseEngFour: "No.",
    keyPhraseChinFive: "她/他不是老师。",
    keyPhrasePinFive: "Tā/tā búshì lǎoshī.",
    keyPhraseEngFive: "She/he is not a teacher",
    firstSpeakerMale: true,
  },

  {
    lessonNumber: "4",
    titleChinese: "认识你很高兴",
    titleEnglish: "Nice to meet you",
    convoLineOne: "李先生，认识你很高兴。",
    convoLineTwo: "我也很高兴。",
    convoLineThree: "你是学生还是老师？",
    convoLineFour: "我是留学生。",
    convoLineFive: "你是中国人还是韩国人？",
    convoLineSix: "我是英国人。",
    convoLineSeven: "哦。",
    translationChinWordOne: "李",
    translationPinWordOne: "Lǐ",
    translationEngWordOne: "a surname",
    translationChinWordTwo: "先生",
    translationPinWordTwo: "xiānsheng",
    translationEngWordTwo: "Mr.",
    translationChinWordThree: "认识",
    translationPinWordThree: "rènshi",
    translationEngWordThree: "recognize",
    translationChinWordFour: "很",
    translationPinWordFour: "hěn",
    translationEngWordFour: "very",
    translationChinWordFive: "高兴",
    translationPinWordFive: "gāoxìng",
    translationEngWordFive: "happy",
    translationChinWordSix: "认识你很高兴",
    translationPinWordSix: "rènshi nǐ hěn gāoxìng",
    translationEngWordSix: "nice to meet you",
    translationChinWordSeven: "也",
    translationPinWordSeven: "yě",
    translationEngWordSeven: "also",
    translationChinWordEight: "还是",
    translationPinWordEight: "háishì",
    translationEngWordEight: "or",
    translationChinWordNine: "留学生",
    translationPinWordNine: "liúxuéshēng",
    translationEngWordNine: "foreign student",
    translationChinWordTen: "英国",
    translationPinWordTen: "yīngguó",
    translationEngWordTen: "Britain",
    sentanceTranslationPinOne: "Lǐ xiānsheng, rènshi nǐ hěn gāoxìng.",
    sentanceTranslationEngOne: "Mr. Li, nice to meet you.",
    sentanceTranslationPinTwo: "wǒ yě hěn gāoxìng.",
    sentanceTranslationEngTwo: "I am also happy.",
    sentanceTranslationPinThree: "nǐ shì xuéshēng háishì lǎoshī?",
    sentanceTranslationEngThree: "Are you a student or a teacher?",
    sentanceTranslationPinFour: "wǒ shì liúxuéshēng.",
    sentanceTranslationEngFour: "I am a foreign student.",
    sentanceTranslationPinFive: "nǐ shì zhōngguórén háishì hánguórén?.",
    sentanceTranslationEngFive: "Are you Chinese or Korean?",
    sentanceTranslationPinSix: "wǒ shì yīngguórén.",
    sentanceTranslationEngSix: "I am British.",
    sentanceTranslationPinSeven: "Ò.",
    sentanceTranslationEngSeven: "oh.",
    keyPhraseChinOne: "认识你很高兴。",
    keyPhrasePinOne: "Rènshi nǐ hěn gāoxìng.",
    keyPhraseEngOne: "Nice to meet you.",
    keyPhraseChinTwo: "我也很高兴。",
    keyPhrasePinTwo: "Wǒ yě hěn gāoxìng.",
    keyPhraseEngTwo: "I am also happy.",
    keyPhraseChinThree: "你是学生还是老师？",
    keyPhrasePinThree: "Nǐ shì xuésheng háishì lǎoshī?",
    keyPhraseEngThree: "Are you a student or a teacher?",
    firstSpeakerMale: false,
  },

  {
    lessonNumber: "5",
    titleChinese: "请进",
    titleEnglish: "Come in",
    convoLineOne: "张女士, 请进。",
    convoLineTwo: "您好。",
    convoLineThree: "请坐。",
    convoLineFour: "谢谢。",
    convoLineFive: "不客气。",
    translationChinWordOne: "张",
    translationPinWordOne: "zhāng",
    translationEngWordOne: "a surname",
    translationChinWordTwo: "女士",
    translationPinWordTwo: "nǚshì",
    translationEngWordTwo: "Mrs.",
    translationChinWordThree: "请",
    translationPinWordThree: "qǐng",
    translationEngWordThree: "please",
    translationChinWordFour: "进",
    translationPinWordFour: "jìn",
    translationEngWordFour: "enter",
    translationChinWordFive: "请进",
    translationPinWordFive: "qǐng jìn",
    translationEngWordFive: "please come in",
    translationChinWordSix: "坐",
    translationPinWordSix: "zuò",
    translationEngWordSix: "sit",
    translationChinWordSeven: "请坐",
    translationPinWordSeven: "qǐng zuò",
    translationEngWordSeven: "please sit down",
    translationChinWordEight: "谢谢",
    translationPinWordEight: "xièxiè",
    translationEngWordEight: "thank you",
    translationChinWordNine: "客气",
    translationPinWordNine: "kèqi",
    translationEngWordNine: "polite",
    translationChinWordTen: "不客气",
    translationPinWordTen: "búkèqi",
    translationEngWordTen: "it’s OK, you are welcome",
    sentanceTranslationPinOne: "Zhāng nǚshì qǐng jìn.",
    sentanceTranslationEngOne: "Mrs. Zhang, please come in.",
    sentanceTranslationPinTwo: "Nínhǎo.",
    sentanceTranslationEngTwo: "Hello.",
    sentanceTranslationPinThree: "Qǐng zuò.",
    sentanceTranslationEngThree: "Please sit.",
    sentanceTranslationPinFour: "Xièxiè.",
    sentanceTranslationEngFour: "Thank you.",
    sentanceTranslationPinFive: "Búkèqi.",
    sentanceTranslationEngFive: "It’s OK.",
    keyPhraseChinOne: "请进 。",
    keyPhrasePinOne: "Qǐng jìn.",
    keyPhraseEngOne: "Please come in.",
    keyPhraseChinTwo: "请坐 。",
    keyPhrasePinTwo: "Qǐng zuò.",
    keyPhraseEngTwo: "Please sit.",
    keyPhraseChinThree: "谢谢 。",
    keyPhrasePinThree: "Xièxiè.",
    keyPhraseEngThree: "Thank you.",
    keyPhraseChinFour: "不客气 。",
    keyPhrasePinFour: "Búkèqi.",
    keyPhraseEngFour: "It’s OK",
    firstSpeakerMale: true,
  },

  {
    lessonNumber: "6",
    titleChinese: "你会说汉语吗？",
    titleEnglish: "Can you speak Chinese?",
    convoLineOne: "你会说汉语吗？",
    convoLineTwo: "我不会说汉语。对不起。",
    convoLineThree: "没关系。你叫什么名字？",
    convoLineFour: "对不起。我听不懂。",
    translationChinWordOne: "会",
    translationPinWordOne: "huì",
    translationEngWordOne: "can, be able to",
    translationChinWordTwo: "说",
    translationPinWordTwo: "shuō",
    translationEngWordTwo: "say/speak",
    translationChinWordThree: "汉语",
    translationPinWordThree: "hànyǔ",
    translationEngWordThree: "Chinese",
    translationChinWordFour: "对不起",
    translationPinWordFour: "duìbuqǐ",
    translationEngWordFour: "sorry",
    translationChinWordFive: "关系",
    translationPinWordFive: "guānxi",
    translationEngWordFive: "connection",
    translationChinWordSix: "没",
    translationPinWordSix: "méi",
    translationEngWordSix: "no/not",
    translationChinWordSeven: "没关系",
    translationPinWordSeven: "méi guānxi",
    translationEngWordSeven: "it’s OK, no problem",
    translationChinWordEight: "听",
    translationPinWordEight: "tīng",
    translationEngWordEight: "listen",
    translationChinWordNine: "懂",
    translationPinWordNine: "dǒng",
    translationEngWordNine: "understand",
    translationChinWordTen: "听不懂",
    translationPinWordTen: "tīng bù dǒng",
    translationEngWordTen: "I don’t understand",
    sentanceTranslationPinOne: "Nǐ huì shuō hànyǔ ma?",
    sentanceTranslationEngOne: "Can you speak Chinese?",
    sentanceTranslationPinTwo: "Wǒ bú huì shuō hànyǔ. Duìbùqǐ.",
    sentanceTranslationEngTwo: "I cannot speak Chinese. Sorry",
    sentanceTranslationPinThree: "Méi guānxi. Nǐ jiào shénme míngzì?",
    sentanceTranslationEngThree: "What is your name?",
    sentanceTranslationPinFour: "Duìbuqǐ. Wǒ tīng bù dǒng.",
    sentanceTranslationEngFour: "Sorry. I don’t understand",
    keyPhraseChinOne: "你会说汉语吗？",
    keyPhrasePinOne: "Nǐ huì shuō hànyǔ ma?",
    keyPhraseEngOne: "Can you speak Chinese?",
    keyPhraseChinTwo: "我不会说汉语 。",
    keyPhrasePinTwo: "Wǒ bú huì shuō hànyǔ.",
    keyPhraseEngTwo: "I cannot speak Chinese.",
    keyPhraseChinThree: "没关系 。",
    keyPhrasePinThree: "Méi guānxi.",
    keyPhraseEngThree: "It’s OK, no problem.",
    keyPhraseChinFour: "对不起。",
    keyPhrasePinFour: "Duìbuqǐ.",
    keyPhraseEngFour: "Sorry.",
    keyPhraseChinFive: "我听不懂。",
    keyPhrasePinFive: "Wǒ tīng bù dǒng.",
    keyPhraseEngFive: "I don’t understand.",
  },
  {
    lessonNumber: "7",
    titleChinese: "厕所在哪儿？",
    titleEnglish: "Where is the toilet?",
    convoLineOne: "请问，你会说中文吗？",
    convoLineTwo: "我会说中文。",
    convoLineThree: "厕所在哪儿？",
    convoLineFour: "卫生间在那儿。",
    convoLineFive: "谢谢。",
    convoLineSix: "不用谢。",
    translationChinWordOne: "问",
    translationPinWordOne: "wèn",
    translationEngWordOne: "ask",
    translationChinWordTwo: "请问",
    translationPinWordTwo: "qǐng wèn",
    translationEngWordTwo: "may I ask... (used before asking a question)",
    translationChinWordThree: "中文",
    translationPinWordThree: "zhōngwén",
    translationEngWordThree: "Chinese",
    translationChinWordFour: "厕所",
    translationPinWordFour: "cèsuǒ",
    translationEngWordFour: "toilet",
    translationChinWordFive: "在",
    translationPinWordFive: "zài",
    translationEngWordFive: "be, at",
    translationChinWordSix: "哪儿",
    translationPinWordSix: "nǎ'er",
    translationEngWordSix: "where?",
    translationChinWordSeven: "卫生间",
    translationPinWordSeven: "wèishēngjiān",
    translationEngWordSeven: "toilet (polite)",
    translationChinWordEight: "那儿",
    translationPinWordEight: "nà'er",
    translationEngWordEight: "there",
    translationChinWordNine: "用",
    translationPinWordNine: "yòng",
    translationEngWordNine: "use",
    translationChinWordTen: "不用谢",
    translationPinWordTen: "búyòng xiè",
    translationEngWordTen: "it’s OK",
    sentanceTranslationPinOne: "Qǐng wèn, nǐ huì shuō zhōngwén ma?",
    sentanceTranslationEngOne: "may I ask, can you speak Chinese?",
    sentanceTranslationPinTwo: "Wǒ huì shuō zhōngwén.",
    sentanceTranslationEngTwo: "I can speak Chinese.",
    sentanceTranslationPinThree: "Cèsuǒ zài nǎ'er?",
    sentanceTranslationEngThree: "Where is the toilet?",
    sentanceTranslationPinFour: "Wèishēngjiān zài nà'er.",
    sentanceTranslationEngFour: "the toilet is there",
    sentanceTranslationPinFive: "Xièxiè.",
    sentanceTranslationEngFive: "Thank you.",
    sentanceTranslationPinSix: "Búyòng xiè.",
    sentanceTranslationEngSix: "It’s OK.",
    keyPhraseChinOne: "请问......",
    keyPhrasePinOne: "Qǐng wèn...",
    keyPhraseEngOne: "May I ask...",
    keyPhraseChinTwo: "我会说中文。",
    keyPhrasePinTwo: "Wǒ huì shuō zhōngwén.",
    keyPhraseEngTwo: "I can speak Chinese.",
    keyPhraseChinThree: "厕所在哪儿？",
    keyPhrasePinThree: "Cèsuǒ zài nǎ'er?",
    keyPhraseEngThree: "Where is the toilet?",
    keyPhraseChinFour: "卫生间在那儿。",
    keyPhrasePinFour: "Wèishēngjiān zài nà'er.",
    keyPhraseEngFour: "The toilet is there.",
    keyPhraseChinFive: "不用谢。",
    keyPhrasePinFive: "Búyòng xiè.",
    keyPhraseEngFive: "It’s OK",
  },
  {
    lessonNumber: "8",
    titleChinese: "这是什么？",
    titleEnglish: "What is this?",
    convoLineOne: "你好，你会说汉语？",
    convoLineTwo: "我会说一点。",
    convoLineThree: "这是什么？",
    convoLineFour: "这是书。",
    convoLineFive: "这是什么？",
    convoLineSix: "这是苹果。",
    convoLineSeven: "那是什么？",
    convoLineEight: "那是椅子。你听得懂吗？",
    convoLineNine: "对。我听得懂。",
    translationChinWordOne: "一点",
    translationPinWordOne: "yìdiǎn",
    translationEngWordOne: "a little bit",
    translationChinWordTwo: "这",
    translationPinWordTwo: "zhè",
    translationEngWordTwo: "this",
    translationChinWordThree: "书",
    translationPinWordThree: "shū",
    translationEngWordThree: "book",
    translationChinWordFour: "苹果",
    translationPinWordFour: "píngguǒ",
    translationEngWordFour: "apple",
    translationChinWordFive: "那",
    translationPinWordFive: "nà/nèi",
    translationEngWordFive: "that",
    translationChinWordSix: "椅子",
    translationPinWordSix: "yǐzi",
    translationEngWordSix: "chair",
    translationChinWordSeven: "得",
    translationPinWordSeven: "de",
    translationEngWordSeven: "used to modify and link words",
    translationChinWordEight: "听得懂",
    translationPinWordEight: "tīng de dǒng",
    translationEngWordEight: "to understand",
    translationChinWordNine: "对",
    translationPinWordNine: "duì",
    translationEngWordNine: "correct, yes",
    sentanceTranslationPinOne: "Nǐhǎo, nǐ huì shuō hànyǔ?",
    sentanceTranslationEngOne: "Hello, do you speak Chinese?",
    sentanceTranslationPinTwo: "Wǒ huì shuō yìdiǎn.",
    sentanceTranslationEngTwo: "I can speak a little.",
    sentanceTranslationPinThree: "Zhè shì shénme?",
    sentanceTranslationEngThree: "What is this?",
    sentanceTranslationPinFour: "Zhè shì shū.",
    sentanceTranslationEngFour: "This is a book.",
    sentanceTranslationPinFive: "Zhè shì shénme?",
    sentanceTranslationEngFive: "What is this?",
    sentanceTranslationPinSix: "Zhè shì píngguǒ.",
    sentanceTranslationEngSix: "This is an apple.",
    sentanceTranslationPinSeven: "Nà shì shénme?",
    sentanceTranslationEngSeven: "What is that?",
    sentanceTranslationPinEight: "Nà shì yǐzi. Nǐ tīng de dǒng ma?",
    sentanceTranslationEngEight: "That is a chair. Do you understand?",
    sentanceTranslationPinNine: "Duì. Wǒ tīng de dǒng.",
    sentanceTranslationEngNine: "Yes. I understand.",
    keyPhraseChinOne: "我会说一点。",
    keyPhrasePinOne: "Wǒ huì shuō yìdiǎn.",
    keyPhraseEngOne: "I can speak a little.",
    keyPhraseChinTwo: "这/那是什么？",
    keyPhrasePinTwo: "Zhè/nà shì shénme?",
    keyPhraseEngTwo: "What is this/that?",
    keyPhraseChinThree: "这/那是书。",
    keyPhrasePinThree: "Zhè/nà shì shū.",
    keyPhraseEngThree: "This/that is a book.",
    keyPhraseChinFour: "你听的懂吗？",
    keyPhrasePinFour: "Nǐ tīng de dǒng ma?",
    keyPhraseEngFour: "Do you understand?",
    keyPhraseChinFive: "对。",
    keyPhrasePinFive: "Duì.",
    keyPhraseEngFive: "Yes/correct.",
    keyPhraseChinSix: "我听的懂。",
    keyPhrasePinSix: "Wǒ tīng de dǒng.",
    keyPhraseEngSix: "I understand.",
  },

  {
    lessonNumber: "9",
    titleChinese: "取款机在哪里？",
    titleEnglish: "Where is the ATM?",
    convoLineOne: "请问，取款机在哪里？",
    convoLineTwo: "在那边。",
    convoLineThree: "在哪儿？",
    convoLineFour: "在那儿，在银行里面。",
    convoLineFive: "谢谢。",
    convoLineSix: "不谢。",
    translationChinWordOne: "取",
    translationPinWordOne: "qǔ",
    translationEngWordOne: "withdraw",
    translationChinWordTwo: "取款",
    translationPinWordTwo: "qǔkuǎn",
    translationEngWordTwo: "withdraw money",
    translationChinWordThree: "机",
    translationPinWordThree: "jī",
    translationEngWordThree: "machine",
    translationChinWordFour: "取款机",
    translationPinWordFour: "qǔkuǎnjī",
    translationEngWordFour: "ATM",
    translationChinWordFive: "哪里",
    translationPinWordFive: "nǎli",
    translationEngWordFive: "where",
    translationChinWordSix: "边",
    translationPinWordSix: "biān",
    translationEngWordSix: "side, area",
    translationChinWordSeven: "那边",
    translationPinWordSeven: "nà biān",
    translationEngWordSeven: "over there",
    translationChinWordEight: "银行",
    translationPinWordEight: "yínháng",
    translationEngWordEight: "bank",
    translationChinWordNine: "里面",
    translationPinWordNine: "lǐmian",
    translationEngWordNine: "inside",
    translationChinWordTen: "不谢",
    translationPinWordTen: "bú xiè",
    translationEngWordTen: "it’s OK",
    sentanceTranslationPinOne: "Qǐng wèn, qǔkuǎnjī zài nǎli?",
    sentanceTranslationEngOne: "May I ask, where is the ATM?",
    sentanceTranslationPinTwo: "Zài nà biān.",
    sentanceTranslationEngTwo: "Over there.",
    sentanceTranslationPinThree: "Zài nǎ'er?",
    sentanceTranslationEngThree: "Where?",
    sentanceTranslationPinFour: "Zài nà'er. Zài yínháng lǐmian.",
    sentanceTranslationEngFour: "There. In the bank.",
    sentanceTranslationPinFive: "Xièxiè.",
    sentanceTranslationEngFive: "Thank you.",
    sentanceTranslationPinSix: "Bú xiè.",
    sentanceTranslationEngSix: "It’s OK",
    keyPhraseChinOne: "取款机在哪里？",
    keyPhrasePinOne: "Qǐng wèn, qǔkuǎnjī zài nǎli?",
    keyPhraseEngOne: "May I ask, where is the ATM?",
    keyPhraseChinTwo: "在那边。",
    keyPhrasePinTwo: "Zài nà biān.",
    keyPhraseEngTwo: "Over there.",
    keyPhraseChinThree: "在哪儿？",
    keyPhrasePinThree: "Zài nǎ'er?",
    keyPhraseEngThree: "Where?",
  },
  {
    lessonNumber: "10",
    titleChinese: "这是你的手机吗？",
    titleEnglish: "Is this your mobile phone?",
    convoLineOne: "这是你的手机吗？",
    convoLineTwo: "是的，这是我的手机。",
    convoLineThree: "我的手机在哪儿？",
    convoLineFour: "我不知道。",
    convoLineFive: "那是谁的杯子？",
    convoLineSix: "那是他的杯子。",
    convoLineSeven: "这是你的钱包吗？",
    convoLineEight: "不是。这是她的。",
    translationChinWordOne: "你的",
    translationPinWordOne: "nǐde",
    translationEngWordOne: "yours",
    translationChinWordTwo: "手机",
    translationPinWordTwo: "shǒujī",
    translationEngWordTwo: "mobile phone",
    translationChinWordThree: "我的",
    translationPinWordThree: "wǒde",
    translationEngWordThree: "my",
    translationChinWordFour: "知道",
    translationPinWordFour: "zhīdào",
    translationEngWordFour: "know",
    translationChinWordFive: "杯子",
    translationPinWordFive: "bēizi",
    translationEngWordFive: "cup",
    translationChinWordSix: "他的",
    translationPinWordSix: "tāde",
    translationEngWordSix: "his",
    translationChinWordSeven: "钱",
    translationPinWordSeven: "qián",
    translationEngWordSeven: "money",
    translationChinWordEight: "包",
    translationPinWordEight: "bāo",
    translationEngWordEight: "bag",
    translationChinWordNine: "钱包",
    translationPinWordNine: "qiánbāo",
    translationEngWordNine: "wallet/purse",
    translationChinWordTen: "她的",
    translationPinWordTen: "tāde",
    translationEngWordTen: "her",
    sentanceTranslationPinOne: "Zhè shì nǐde shǒujī ma?",
    sentanceTranslationEngOne: "Is this your mobile phone?",
    sentanceTranslationPinTwo: "Shìde. Zhè shì wǒde shǒujī.",
    sentanceTranslationEngTwo: "Yes. This is my mobile phone",
    sentanceTranslationPinThree: "Wǒde shǒujī zài nǎ'er?",
    sentanceTranslationEngThree: "Where is my mobile phone?",
    sentanceTranslationPinFour: "Wǒ bù zhīdào.",
    sentanceTranslationEngFour: "I don’t know.",
    sentanceTranslationPinFive: "Nà shì sheíde bēizi?",
    sentanceTranslationEngFive: "Whose cup is that cup?",
    sentanceTranslationPinSix: "Nà shì tāde bēizi.",
    sentanceTranslationEngSix: "That is his cup.",
    sentanceTranslationPinSeven: "Zhè shì nǐde qiánbāo ma?",
    sentanceTranslationEngSeven: "Is this yours?",
    sentanceTranslationPinEight: "Búshì. Zhè shì tāde.",
    sentanceTranslationEngEight: "No. This is hers.",
    keyPhraseChinOne: "这是你的手机吗？",
    keyPhrasePinOne: "Zhè shì nǐde shǒujī ma?",
    keyPhraseEngOne: "Is this your mobile phone?",
    keyPhraseChinTwo: "这是我的手机。",
    keyPhrasePinTwo: "Zhè shì wǒde shǒujī.",
    keyPhraseEngTwo: "This is my mobile phone",
    keyPhraseChinThree: "我不知道。",
    keyPhrasePinThree: "Wǒ bù zhīdào.",
    keyPhraseEngThree: "I don’t know.",
    keyPhraseChinFour: "那是谁的杯子？",
    keyPhrasePinFour: "Nà shì sheí de bēizi?",
    keyPhraseEngFour: "Whose is that cup?",
    keyPhraseChinFive: "那是他的杯子。",
    keyPhrasePinFive: "Nà shì tāde bēizi.",
    keyPhraseEngFive: "That is his cup.",
  },
];
