export const lessonOne = {
  lessonNumber: "1",
  titleChinese: "你叫什么名字？",
  titleEnglish: " What is your name?",
  convoLineOne: "你好。",
  convoLineTwo: "您好。",
  convoLineThree: "你叫什么名字？",
  convoLineFour: "我叫朱虹。你叫什么名字？",
  convoLineFive: "我叫刘明。",
  translationChinWordOne: "你",
  translationPinWordOne: "nǐ",
  translationEngWordOne: "you",
  translationChinWordTwo: "好",
  translationPinWordTwo: "hǎo",
  translationEngWordTwo: "good",
  translationChinWordThree: "你好",
  translationPinWordThree: "nǐ hǎo",
  translationEngWordThree: "hello",
  translationChinWordFour: "您",
  translationPinWordFour: "nín",
  translationEngWordFour: "you (polite)",
  translationChinWordFive: "您好",
  translationPinWordFive: "nínhǎo",
  translationEngWordFive: "hello (polite)",
  translationChinWordSix: "叫",
  translationPinWordSix: "jiào",
  translationEngWordSix: "called, named",
  translationChinWordSeven: "什么",
  translationPinWordSeven: "shénme",
  translationEngWordSeven: "what",
  translationChinWordEight: "名字",
  translationPinWordEight: "míngzi",
  translationEngWordEight: "name",
  translationChinWordNine: "我",
  translationPinWordNine: "wǒ",
  translationEngWordNine: "I",
  translationChinWordTen: "朱虹",
  translationPinWordTen: "zhū hóng",
  translationEngWordTen: "a female name",
  translationChinWordEleven: "刘明",
  translationPinWordEleven: "líu míng",
  translationEngWordEleven: "a male name",
  sentanceTranslationPinOne: "Nǐ hǎo.",
  sentanceTranslationEngOne: "Hello.",
  sentanceTranslationPinTwo: "Nínhǎo.",
  sentanceTranslationEngTwo: "Hello.",
  sentanceTranslationPinThree: "Nǐ jìao shénme míngzi?",
  sentanceTranslationEngThree: "What is your name?",
  sentanceTranslationPinFour: "Wǒ jìao Zhū Hóng. Nǐ jìao shénme míngzi?",
  sentanceTranslationEngFour: "I’m called Zhu Hong. What is your name?",
  sentanceTranslationPinFive: "Wǒ jìao Líu Míng.",
  sentanceTranslationEngFive: "I’m called Liu Ming.",
  keyPhraseChinOne: "你好。",
  keyPhrasePinOne: "Nǐ hǎo.",
  keyPhraseEngOne: "Hello.",
  keyPhraseChinTwo: "您好。",
  keyPhrasePinTwo: "Nínhǎo.",
  keyPhraseEngTwo: "Hello (polite).",
  keyPhraseChinThree: "你叫什么名字？",
  keyPhrasePinThree: "Nǐ jìao shénme míngzi?",
  keyPhraseEngThree: "What is your name?",
  keyPhraseChinFour: "我叫......",
  keyPhrasePinFour: "Wǒ jìao...",
  keyPhraseEngFour: "I’m called...",
};

export const lessonTwo = {
  lessonNumber: "2",
  titleChinese: "你是中国人吗？",
  titleEnglish: "Are you Chinese?",
  convoLineOne: "您贵姓？",
  convoLineTwo: "我姓朱。",
  convoLineThree: "你是中国人吗?",
  convoLineFour: "是的，我是中国人。你是美国人吗？",
  convoLineFive: "是的，我是美国人。",
  translationChinWordOne: "贵",
  translationPinWordOne: "guì",
  translationEngWordOne: "expensive, honorable",
  translationChinWordTwo: "姓",
  translationPinWordTwo: "xìng",
  translationEngWordTwo: "surname",
  translationChinWordThree: "贵姓",
  translationPinWordThree: "guìxìng",
  translationEngWordThree: "surname (polite)",
  translationChinWordFour: "是",
  translationPinWordFour: "shì",
  translationEngWordFour: "is, be, am",
  translationChinWordFive: "国",
  translationPinWordFive: "guó",
  translationEngWordFive: "country, nation",
  translationChinWordSix: "中国",
  translationPinWordSix: "zhōngguó",
  translationEngWordSix: "China",
  translationChinWordSeven: "人",
  translationPinWordSeven: "rén",
  translationEngWordSeven: "person",
  translationChinWordEight: "中国人",
  translationPinWordEight: "zhōngguórén",
  translationEngWordEight: "Chinese",
  translationChinWordNine: "吗",
  translationPinWordNine: "ma",
  translationEngWordNine: "(used at the end of a question)",
  translationChinWordTen: "是的",
  translationPinWordTen: "shìde",
  translationEngWordTen: "yes",
  translationChinWordEleven: "美",
  translationPinWordEleven: "měi",
  translationEngWordEleven: "beautiful",
  translationChinWordTwelve: "美国",
  translationPinWordTwelve: "měiguó",
  translationEngWordTwelve: "USA",
  sentanceTranslationPinOne: "Nín guìxìng?",
  sentanceTranslationEngOne: "What is your surname?",
  sentanceTranslationPinTwo: "Wǒ xìng zhū.",
  sentanceTranslationEngTwo: "My surname is Zhu.",
  sentanceTranslationPinThree: "Nǐ shì zhōngguórén ma?",
  sentanceTranslationEngThree: "Are you Chinese?",
  sentanceTranslationPinFour: "Shìde. Wǒ shì zhōngguórén. Nǐ shì měiguórén ma?",
  sentanceTranslationEngFour: "Yes. I am Chinese. Are you American?",
  sentanceTranslationPinFive: "Shìde. Wǒ shì měiguórén.",
  sentanceTranslationEngFive: "Yes. I am American",
  keyPhraseChinOne: "您贵姓？",
  keyPhrasePinOne: "Nín guìxìng?",
  keyPhraseEngOne: "What is your surname?",
  keyPhraseChinTwo: "我姓......",
  keyPhrasePinTwo: "Wǒ xìng…",
  keyPhraseEngTwo: "My surname is…",
  keyPhraseChinThree: "你是中国人吗？",
  keyPhrasePinThree: "Nǐ shì zhōngguórén ma?",
  keyPhraseEngThree: "Are you Chinese?",
  keyPhraseChinFour: "是的。",
  keyPhrasePinFour: "Shìde.",
  keyPhraseEngFour: "Yes.",
  keyPhraseChinFive: "我是中国人。",
  keyPhrasePinFive: "Wǒ shì zhōngguórén.",
  keyPhraseEngFive: "I am Chinese.",
};

export const lessonThree = {
  lessonNumber: "3",
  titleChinese: "她是谁？",
  titleEnglish: "Who is she?",
  convoLineOne: "她是谁？",
  convoLineTwo: "她是明美。",
  convoLineThree: "她是韩国人吗？",
  convoLineFour: "不是。她是日本人。",
  convoLineFive: "哦，她是老师吗？",
  convoLineSix: "不是，她不是老师。她是学生。",
  convoLineSeven: "谁是老师？",
  convoLineEight: "他是老师。",
  translationChinWordOne: "她",
  translationPinWordOne: "tā",
  translationEngWordOne: "she",
  translationChinWordTwo: "谁",
  translationPinWordTwo: "shéi",
  translationEngWordTwo: "who",
  translationChinWordThree: "明美",
  translationPinWordThree: "míngměi",
  translationEngWordThree: "a female name",
  translationChinWordFour: "韩国",
  translationPinWordFour: "hánguó",
  translationEngWordFour: "Korea",
  translationChinWordFive: "日本",
  translationPinWordFive: "rìběn",
  translationEngWordFive: "Japan",
  translationChinWordSix: "哦",
  translationPinWordSix: "ò",
  translationEngWordSix: "oh (use to express understanding)",
  translationChinWordSeven: "老师",
  translationPinWordSeven: "lǎoshī",
  translationEngWordSeven: "teacher",
  translationChinWordEight: "不",
  translationPinWordEight: "bù",
  translationEngWordEight: "not, no",
  translationChinWordNine: "不是",
  translationPinWordNine: "búshì",
  translationEngWordNine: "is not, to not be",
  translationChinWordTen: "学生",
  translationPinWordTen: "xuésheng",
  translationEngWordTen: "student",
  translationChinWordEleven: "他",
  translationPinWordEleven: "tā",
  translationEngWordEleven: "he",
  sentanceTranslationPinOne: "Tā shì shéi?",
  sentanceTranslationEngOne: "Who is she?",
  sentanceTranslationPinTwo: "Tā shì míngměi.",
  sentanceTranslationEngTwo: "She is Ming Mei.",
  sentanceTranslationPinThree: "Tā shì hánguórén ma?.",
  sentanceTranslationEngThree: "Is she Korean?",
  sentanceTranslationPinFour: "Búshì. Tā shì rìběnrén.",
  sentanceTranslationEngFour: "No. She is Japanese.",
  sentanceTranslationPinFive: "Ò, tā shì lǎoshī ma?",
  sentanceTranslationEngFive: " Oh. Is she a teacher?",
  sentanceTranslationPinSix: "Búshì, tā búshì lǎoshī. Tā shì xuésheng.",
  sentanceTranslationEngSix: "No. She is not a teacher. She is a student",
  sentanceTranslationPinSeven: "Shéi shì lǎoshī?",
  sentanceTranslationEngSeven: "Who is the teacher?",
  sentanceTranslationPinEight: "Tā shì lǎoshī.",
  sentanceTranslationEngEight: " He is the teacher",
  keyPhraseChinOne: "她/他是谁？",
  keyPhrasePinOne: "Tā/tā shì sheí?",
  keyPhraseEngOne: "Who is she/he?",
  keyPhraseChinTwo: "她/他是......",
  keyPhrasePinTwo: "Tā/tā shì...",
  keyPhraseEngTwo: "She/he is…",
  keyPhraseChinThree: "她/他是老师吗？",
  keyPhrasePinThree: "Tā/tā shì lǎoshī ma?",
  keyPhraseEngThree: "Is she/he a teacher?",
  keyPhraseChinFour: "不是。",
  keyPhrasePinFour: "Búshì.",
  keyPhraseEngFour: "No.",
  keyPhraseChinFive: "她/他不是老师。",
  keyPhrasePinFive: "Tā/tā búshì lǎoshī.",
  keyPhraseEngFive: "She/he is not a teacher",
};

export const lessonFour = {
  lessonNumber: "4",
  titleChinese: "认识你很高兴",
  titleEnglish: "Nice to meet you",
  convoLineOne: "李先生，认识你很高兴。",
  convoLineTwo: "我也很高兴。",
  convoLineThree: "你是学生还是老师？",
  convoLineFour: "我是留学生。",
  convoLineFive: "你是中国人还是韩国人？",
  convoLineSix: "我是英国人。",
  convoLineSeven: "哦。",
  translationChinWordOne: "李",
  translationPinWordOne: "Lǐ",
  translationEngWordOne: "a surname",
  translationChinWordTwo: "先生",
  translationPinWordTwo: "xiānsheng",
  translationEngWordTwo: "Mr.",
  translationChinWordThree: "认识",
  translationPinWordThree: "rènshi",
  translationEngWordThree: "recognize",
  translationChinWordFour: "很",
  translationPinWordFour: "hěn",
  translationEngWordFour: "very",
  translationChinWordFive: "高兴",
  translationPinWordFive: "gāoxìng",
  translationEngWordFive: "happy",
  translationChinWordSix: "认识你很高兴",
  translationPinWordSix: "rènshi nǐ hěn gāoxìng",
  translationEngWordSix: "nice to meet you",
  translationChinWordSeven: "也",
  translationPinWordSeven: "yě",
  translationEngWordSeven: "also",
  translationChinWordEight: "还是",
  translationPinWordEight: "háishì",
  translationEngWordEight: "or",
  translationChinWordNine: "留学生",
  translationPinWordNine: "liúxuéshēng",
  translationEngWordNine: "foreign student",
  translationChinWordTen: "英国",
  translationPinWordTen: "yīngguó",
  translationEngWordTen: "Britain",
  sentanceTranslationPinOne: "Lǐ xiānsheng, rènshi nǐ hěn gāoxìng.",
  sentanceTranslationEngOne: "Mr. Li, nice to meet you.",
  sentanceTranslationPinTwo: "wǒ yě hěn gāoxìng.",
  sentanceTranslationEngTwo: "I am also happy.",
  sentanceTranslationPinThree: "nǐ shì xuéshēng háishì lǎoshī?",
  sentanceTranslationEngThree: "Are you a student or a teacher?",
  sentanceTranslationPinFour: "wǒ shì liúxuéshēng.",
  sentanceTranslationEngFour: "I am a foreign student.",
  sentanceTranslationPinFive: "nǐ shì zhōngguórén háishì hánguórén?.",
  sentanceTranslationEngFive: "Are you Chinese or Korean?",
  sentanceTranslationPinSix: "wǒ shì yīngguórén.",
  sentanceTranslationEngSix: "I am British.",
  sentanceTranslationPinSeven: "Ò.",
  sentanceTranslationEngSeven: "oh.",
  keyPhraseChinOne: "认识你很高兴。",
  keyPhrasePinOne: "Rènshi nǐ hěn gāoxìng.",
  keyPhraseEngOne: "Nice to meet you.",
  keyPhraseChinTwo: "我也很高兴。",
  keyPhrasePinTwo: "Wǒ yě hěn gāoxìng.",
  keyPhraseEngTwo: "I am also happy.",
  keyPhraseChinThree: "你是学生还是老师？",
  keyPhrasePinThree: "Nǐ shì xuésheng háishì lǎoshī?",
  keyPhraseEngThree: "Are you a student or a teacher?",
};

export const lessonFive = {
  lessonNumber: "5",
  titleChinese: "请进",
  titleEnglish: "Come in",
  convoLineOne: "张女士, 请进。",
  convoLineTwo: "您好。",
  convoLineThree: "请坐。",
  convoLineFour: "谢谢。",
  convoLineFive: "不客气。",
  translationChinWordOne: "张",
  translationPinWordOne: "zhāng",
  translationEngWordOne: "a surname",
  translationChinWordTwo: "女士",
  translationPinWordTwo: "nǚshì",
  translationEngWordTwo: "Mrs.",
  translationChinWordThree: "请",
  translationPinWordThree: "qǐng",
  translationEngWordThree: "please",
  translationChinWordFour: "进",
  translationPinWordFour: "jìn",
  translationEngWordFour: "enter",
  translationChinWordFive: "请进",
  translationPinWordFive: "qǐng jìn",
  translationEngWordFive: "please come in",
  translationChinWordSix: "坐",
  translationPinWordSix: "zuò",
  translationEngWordSix: "sit",
  translationChinWordSeven: "请坐",
  translationPinWordSeven: "qǐng zuò",
  translationEngWordSeven: "please sit down",
  translationChinWordEight: "谢谢",
  translationPinWordEight: "xièxiè",
  translationEngWordEight: "thank you",
  translationChinWordNine: "客气",
  translationPinWordNine: "kèqi",
  translationEngWordNine: "polite",
  translationChinWordTen: "不客气",
  translationPinWordTen: "búkèqi",
  translationEngWordTen: "it’s OK, you are welcome",
  sentanceTranslationPinOne: "Zhāng nǚshì qǐng jìn.",
  sentanceTranslationEngOne: "Mrs. Zhang, please come in.",
  sentanceTranslationPinTwo: "Nínhǎo.",
  sentanceTranslationEngTwo: "Hello.",
  sentanceTranslationPinThree: "Qǐng zuò.",
  sentanceTranslationEngThree: "Please sit.",
  sentanceTranslationPinFour: "Xièxiè.",
  sentanceTranslationEngFour: "Thank you.",
  sentanceTranslationPinFive: "Búkèqi.",
  sentanceTranslationEngFive: "It’s OK.",
  keyPhraseChinOne: "请进 。",
  keyPhrasePinOne: "Qǐng jìn.",
  keyPhraseEngOne: "Please come in.",
  keyPhraseChinTwo: "请坐 。",
  keyPhrasePinTwo: "Qǐng zuò.",
  keyPhraseEngTwo: "Please sit.",
  keyPhraseChinThree: "谢谢 。",
  keyPhrasePinThree: "Xièxiè.",
  keyPhraseEngThree: "Thank you.",
  keyPhraseChinFour: "不客气 。",
  keyPhrasePinFour: "Búkèqi.",
  keyPhraseEngFour: "It’s OK",
};
